# Generated by Django 5.1.7 on 2025-05-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_alter_task_options_task_created_alter_task_duedate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'duedate']},
        ),
        migrations.AddField(
            model_name='task',
            name='custom_status',
            field=models.CharField(blank=True, help_text="If status is 'Custom', specify here", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('custom', 'Custom')], default='not_started', max_length=20),
        ),
    ]
