# Generated by Django 5.1.7 on 2025-05-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_taskgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='color',
            field=models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Light Blue'), ('secondary', 'Gray'), ('dark', 'Dark'), ('purple', 'Purple'), ('pink', 'Pink'), ('orange', 'Orange')], default='primary', max_length=20),
        ),
    ]
